-- Continuação da revisão autoral das 64 questões de Comunicação Organizacional.
-- Os textos abaixo são específicos para o conceito e a redação de cada item.

WITH guides(id,topic,concept,evidence,analysis,trap,strategy,tips) AS (VALUES
('1c0c479a-9c41-4f90-b3fd-5271a7891b75'::uuid,
 'Comunicação Organizacional → Comunicação Institucional → Identidade, imagem e reputação',
 'Identidade é o conjunto de características pelas quais a organização se define; imagem é a percepção formada por um público em determinado momento; reputação é a avaliação consolidada ao longo do tempo. A comunicação institucional articula esses elementos perante os públicos.',
 'O item atribui à comunicação institucional justamente o fortalecimento da identidade e de seus reflexos externos: imagem e reputação.',
 'A organização apresenta missão, valores, posicionamentos e condutas por meio da comunicação institucional. Essa expressão pública influencia a imagem percebida e, quando confirmada por práticas consistentes ao longo do tempo, contribui para a reputação.'||E'\n\n'||'Como o item relaciona corretamente a área a esses três elementos e não os trata como sinônimos, está certo.',
 '',
 'Em questões desse tema, diferencie a essência declarada pela organização, a percepção momentânea dos públicos e a avaliação acumulada: identidade, imagem e reputação, respectivamente.',
 jsonb_build_array('Identidade = quem a organização é; imagem = como é percebida; reputação = avaliação consolidada.')),

('1e6edfcb-15b5-4754-9bbf-3bd907831298'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Linguagem cidadã e precisão',
 'Linguagem cidadã torna a informação pública clara, direta e acessível sem eliminar dados, requisitos ou precisão conceitual. Simplificar a forma de apresentação não significa empobrecer o conteúdo.',
 'O erro está em afirmar que clareza “elimina precisão técnica”; uma comunicação pode explicar um termo especializado e conservar integralmente seu significado.',
 'Órgãos públicos lidam com normas e procedimentos técnicos, mas devem traduzi-los para que o cidadão compreenda direitos, deveres e serviços. Podem manter o termo necessário e acrescentar definição, exemplo ou orientação prática.'||E'\n\n'||'A consequência proposta pelo item — evitar linguagem cidadã — também é incorreta, pois a clareza amplia o acesso efetivo à informação.',
 'A banca cria uma falsa oposição entre linguagem acessível e exatidão técnica.',
 'Quando a questão opuser simplicidade a precisão, verifique se simplificar significa retirar informação essencial ou apenas reorganizar e explicar o conteúdo.',
 jsonb_build_array('Linguagem cidadã reduz burocratês, não a precisão.','Clareza e rigor técnico são compatíveis.')),

('22da1539-ab60-4f88-b67d-82b8aedb4709'::uuid,
 'Comunicação Organizacional → Comunicação Integrada → Dimensões da comunicação',
 'Comunicação organizacional abrange os fluxos pelos quais a instituição se relaciona com trabalhadores, administração, mercado, imprensa, governo e sociedade. Ela integra dimensões interna, administrativa, institucional e mercadológica.',
 'As expressões “restringe-se” e “exclui” reduzem indevidamente o campo ao relacionamento com jornalistas.',
 'Assessoria de imprensa é apenas uma atividade da comunicação institucional. A organização também precisa comunicar processos internamente, apoiar rotinas administrativas, dialogar com consumidores ou usuários e coordenar sua presença pública.'||E'\n\n'||'Como o item exclui componentes reconhecidos da comunicação organizacional, apresenta definição incompleta e deve ser julgado errado.',
 'A armadilha consiste em tomar uma atividade visível — relacionamento com a imprensa — pelo campo organizacional inteiro.',
 'Liste os públicos e fluxos citados. Se a definição aceitar apenas imprensa ou público externo, ela provavelmente está reduzindo a comunicação organizacional.',
 jsonb_build_array('Comunicação organizacional é ampla e integra fluxos internos e externos.')),

('2538e289-03b8-49d8-9b9d-82c99fc787ed'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Comunicação governamental',
 'Comunicação pública orienta-se ao interesse coletivo, à cidadania e ao diálogo sobre assuntos públicos. Comunicação governamental parte de órgãos e gestões de governo; pode integrar a comunicação pública, mas os conceitos não são automaticamente equivalentes.',
 'Os termos absolutos “sempre idênticas” e “exclusivamente ao governante” contradizem a finalidade cidadã da comunicação pública.',
 'Uma gestão pode divulgar políticas, serviços e decisões, mas deve fazê-lo em benefício da sociedade e sob os princípios de publicidade e impessoalidade. A comunicação pública também envolve atores sociais fora do governo e não existe para promover a pessoa eleita.'||E'\n\n'||'O item confunde emissor governamental com finalidade pública e, por isso, está errado.',
 'A banca mistura quem comunica com a finalidade da comunicação.',
 'Separe três perguntas: quem emite, qual assunto é tratado e a quem a comunicação serve. Governo como emissor não autoriza promoção do governante.',
 jsonb_build_array('Comunicação pública serve ao interesse coletivo.','Governamental indica origem no governo, não promoção pessoal.')),

('26e8d4a2-2356-408a-9d02-610839e911a9'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Impessoalidade na divulgação oficial',
 'A comunicação estatal deve informar políticas, serviços e resultados com finalidade pública. A impessoalidade impede que publicidade e canais oficiais sejam utilizados para exaltar nomes, imagens ou marcas pessoais de autoridades.',
 'O erro está em dizer que a autoria política “prevalece” sobre a impessoalidade; o resultado positivo da ação não suspende o princípio constitucional.',
 'O cidadão pode ser informado sobre a iniciativa, o órgão responsável, o serviço prestado e os resultados alcançados. O que não se admite é converter essa divulgação em promoção do gestor, como se a realização pública fosse benefício pessoal.'||E'\n\n'||'Como o item subordina a impessoalidade ao interesse promocional da autoridade, está errado.',
 'A armadilha usa um resultado público verdadeiro para justificar uma finalidade promocional proibida.',
 'Em peças oficiais, procure o foco da mensagem: serviço e orientação ao cidadão são legítimos; enaltecimento pessoal do agente indica desvio de finalidade.',
 jsonb_build_array('Resultado positivo não autoriza promoção pessoal.','Publicidade estatal deve permanecer impessoal.')),

('3826e709-bf8a-4077-82e1-345c50ad36d8'::uuid,
 'Comunicação Organizacional → Públicos estratégicos → Público interno',
 'Público interno reúne grupos que participam da rotina, dos processos e da cultura organizacional. O vínculo pode ser estatutário, empregatício, contratual, formativo ou gerencial.',
 'Servidores, empregados, terceirizados, estagiários e gestores mantêm relação direta com o funcionamento cotidiano da instituição, por isso podem compor o público interno.',
 'A classificação de público não se limita ao quadro permanente. Terceirizados e estagiários também recebem orientações, usam canais internos e influenciam a experiência organizacional; gestores integram e coordenam esses fluxos.'||E'\n\n'||'A enumeração apresentada é compatível com o conceito e o item está certo.',
 '',
 'Classifique o público pelo tipo de relação com a organização, não apenas pelo regime jurídico do vínculo.',
 jsonb_build_array('Público interno inclui vínculos permanentes e temporários ligados à rotina institucional.')),

('3d584e3a-bc0d-44fc-98b1-bb5cc0d0f9b2'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Linguagem cidadã e acessibilidade',
 'Linguagem cidadã organiza a informação para que pessoas com diferentes níveis de escolaridade compreendam direitos, serviços e procedimentos. Emprega frases diretas, explica siglas e termos técnicos e orienta ações concretas.',
 'A finalidade indicada — simplificar o jargão técnico-burocrático para ampliar compreensão — corresponde ao núcleo da linguagem cidadã.',
 'O item não propõe omitir requisitos jurídicos ou técnicos; propõe tornar sua apresentação acessível. Essa tradução reduz barreiras informacionais e permite ao cidadão usar serviços e exercer direitos.'||E'\n\n'||'Como inclusão e transparência dependem de compreensão real, a afirmação está correta.',
 '',
 'Verifique se a simplificação preserva o conteúdo essencial e facilita uma ação do cidadão; esses são sinais de linguagem cidadã bem aplicada.',
 jsonb_build_array('Informação pública só é acessível quando pode ser compreendida e utilizada.')),

('42325200-d4ca-489c-b5ed-7a45d29f2737'::uuid,
 'Comunicação Organizacional → Comunicação Institucional → Coerência entre discurso e prática',
 'A reputação institucional resulta da comparação contínua entre o que a organização declara e o que efetivamente faz. Identidade e discurso sem correspondência prática produzem perda de confiança.',
 'O item exige alinhamento entre discurso público, identidade organizacional e práticas reais, relação necessária para credibilidade.',
 'Missão, valores e compromissos comunicados criam expectativas nos públicos. Se decisões e condutas contradizem essas mensagens, a comunicação não consegue sustentar sozinha uma imagem positiva.'||E'\n\n'||'Ao afirmar que a comunicação institucional deve buscar coerência entre esses elementos, o item descreve corretamente a gestão reputacional.',
 '',
 'Em questões de reputação, confronte promessa institucional e comportamento observado; comunicação não compensa incoerência operacional persistente.',
 jsonb_build_array('Reputação depende de coerência entre dizer e fazer.')),

('43293a20-bfff-4c86-a227-d8d8b1ff32db'::uuid,
 'Comunicação Organizacional → Gestão de crise → Resposta e monitoramento',
 'Gestão de crise comunicacional organiza apuração, decisão, porta-voz, atualização e acompanhamento da repercussão. Rapidez deve coexistir com precisão; transparência é exercida dentro dos limites legais e do que já foi confirmado.',
 'Rapidez, centralização de informações, transparência possível e monitoramento são componentes compatíveis de uma resposta coordenada à crise.',
 'A demora cria vazio informacional, enquanto mensagens desencontradas alimentam boatos. Centralizar não significa ocultar, mas garantir uma fonte coordenada; monitorar permite corrigir desinformação e adaptar orientações.'||E'\n\n'||'Como o item reúne práticas adequadas sem exigir divulgação irresponsável, está certo.',
 'A expressão “transparência possível” evita confundir transparência com divulgação de dados sigilosos ou ainda não confirmados.',
 'Avalie se o protocolo equilibra velocidade, confirmação dos fatos, unidade de mensagem e acompanhamento da reação pública.',
 jsonb_build_array('Em crise: apure, coordene, informe e monitore.','Rapidez sem precisão também amplia o risco.')),

('474c315b-73dd-42bb-9218-7cbbfbb208f5'::uuid,
 'Comunicação Organizacional → Comunicação Interna → Reputação e públicos externos',
 'Comunicação interna influencia alinhamento, clima, comportamento e qualidade do atendimento. Trabalhadores também relatam experiências e interagem com públicos externos, afetando a imagem da instituição.',
 'O erro está em considerar a comunicação interna “irrelevante” e sem efeito externo; a fronteira entre públicos internos e reputação não é impermeável.',
 'Colaboradores bem informados tendem a prestar atendimento mais coerente e explicar decisões com menos ruído. Conflitos, desinformação e desalinhamento internos podem chegar a usuários, imprensa e redes sociais.'||E'\n\n'||'Assim, embora tenha foco interno, essa comunicação produz reflexos reputacionais e o item está errado.',
 'A banca confunde o destinatário imediato da mensagem com o alcance de seus efeitos.',
 'Diferencie público-alvo direto e impacto indireto. Uma ação interna pode influenciar fortemente a experiência do público externo.',
 jsonb_build_array('Comunicação interna afeta clima, atendimento e reputação.')),

('4e521a41-6176-4223-abc9-d1ff9e4ebef4'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Interesse público e curiosidade',
 'Interesse público diz respeito à relevância coletiva de uma informação para direitos, decisões, segurança, fiscalização ou vida social. Curiosidade pública é apenas aquilo que desperta atenção, sem necessariamente possuir utilidade social.',
 'O item afirma somente que os conceitos não se confundem automaticamente, distinção correta entre relevância coletiva e atração do público.',
 'Um fato privado pode gerar grande curiosidade e ainda não justificar exposição. Já uma informação técnica sobre orçamento ou saúde pode despertar menos interesse imediato e ser fundamental para a cidadania.'||E'\n\n'||'Como audiência potencial não determina sozinha relevância pública, o item está certo.',
 '',
 'Pergunte qual consequência coletiva justifica a divulgação. Se houver apenas desejo de saber, pode existir curiosidade sem interesse público.',
 jsonb_build_array('Interesse do público não é necessariamente interesse público.')),

('514b7ca9-e7ab-4ba3-8378-3a959bdc872f'::uuid,
 'Comunicação Organizacional → Identidade institucional → Elementos constitutivos',
 'Identidade institucional reúne atributos que orientam como a organização se define, age e se apresenta. Inclui propósito, valores, linguagem, símbolos, cultura, condutas e posicionamentos.',
 'A lista do item combina elementos simbólicos — linguagem e símbolos — com elementos estratégicos e comportamentais — missão, valores, conduta e posicionamento.',
 'Logotipo e identidade visual expressam parte da identidade, mas não a esgotam. Decisões, padrões de atendimento e compromissos também comunicam quem a instituição é.'||E'\n\n'||'Como todos os elementos enumerados podem integrar a identidade institucional, o julgamento correto é certo.',
 '',
 'Desconfie de definições que reduzam identidade a marca visual; procure também propósito, cultura e comportamento organizacional.',
 jsonb_build_array('Identidade institucional combina símbolos, discurso e modo de agir.')),

('54cf8b13-9850-4a72-ad36-0b902c71fb31'::uuid,
 'Comunicação Organizacional → Comunicação Digital → Engajamento',
 'Engajamento representa ações ativas do público em relação ao conteúdo. Plataformas podem registrar diferentes interações, como curtidas, comentários, compartilhamentos, salvamentos, respostas e cliques qualificados.',
 'Todos os exemplos citados exigem alguma reação do usuário além da simples exposição ao conteúdo.',
 'As ações não têm necessariamente o mesmo peso: compartilhar pode indicar intenção distinta de curtir, e salvar pode apontar utilidade futura. Ainda assim, todas podem compor medidas de engajamento conforme o objetivo e a plataforma.'||E'\n\n'||'A enumeração é tecnicamente adequada e o item está certo.',
 '',
 'Antes de somar engajamento, identifique quais interações a plataforma mede e quais delas se relacionam à meta da ação.',
 jsonb_build_array('Engajamento mede reação ativa, não mera visualização.')),

('61cc4005-50f6-4eb1-9de6-0fda9ea747df'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Accountability institucional',
 'Prestação de contas é uma dimensão da comunicação pública e institucional porque traduz decisões, despesas e resultados para os públicos interessados. Relatórios não são documentos exclusivamente internos quando tratam do uso de recursos públicos.',
 'As expressões “incompatível” e “devem permanecer restritos” negam a função pública de relatórios de gestão e prestação de contas.',
 'A instituição precisa organizar dados internamente, mas também apresentar informações relevantes à sociedade e aos órgãos de controle. Essa divulgação permite fiscalização e pode fortalecer confiança quando é íntegra e compreensível.'||E'\n\n'||'Ao impor sigilo geral a relatórios públicos, o item contraria accountability e está errado.',
 'A banca trata prestação de contas como rotina administrativa privada, ignorando seus destinatários externos.',
 'Verifique a natureza do recurso e do documento. Se envolvem atuação pública, a regra é transparência, ressalvadas hipóteses legais específicas de sigilo.',
 jsonb_build_array('Prestação de contas conecta comunicação institucional e controle social.')),

('63903eca-3247-468b-b654-af2a36f45313'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Tradução do burocratês',
 'Linguagem cidadã converte redação técnica ou burocrática em informação clara e orientada às necessidades do usuário. Ela preserva condições, prazos e responsabilidades essenciais.',
 'O item define corretamente a prática ao relacionar tradução de termos técnicos com compreensão pelo cidadão.',
 'Acessibilidade textual pode envolver explicar siglas, preferir ordem direta, organizar etapas e usar exemplos. O objetivo não é infantilizar o leitor, mas eliminar barreiras desnecessárias ao uso de direitos e serviços.'||E'\n\n'||'A finalidade e o método descritos são compatíveis; portanto, o item está certo.',
 '',
 'Analise se a reescrita responde ao que o cidadão precisa saber e fazer sem retirar requisito importante.',
 jsonb_build_array('Linguagem cidadã transforma informação disponível em informação utilizável.')),

('64bafc53-a083-4da5-b6a3-2618345b963a'::uuid,
 'Comunicação Organizacional → Métricas digitais → Diagnóstico de CTR',
 'CTR é a proporção entre cliques e impressões. Taxa baixa indica que poucas exibições geraram clique, mas não identifica sozinha a causa do desempenho.',
 'Chamada, segmentação, criativo, oferta e adequação ao público são hipóteses plausíveis para investigar quando o CTR está baixo.',
 'Uma chamada pouco clara pode não estimular o clique; segmentação inadequada exibe a peça a pessoas sem interesse; criativo e oferta também influenciam resposta. Como diferentes fatores produzem o mesmo sintoma, a métrica orienta diagnóstico, não prova uma causa única.'||E'\n\n'||'O item usa corretamente “pode indicar” e está certo.',
 'A expressão modal evita concluir causalidade automática a partir de uma única métrica.',
 'Compare segmentos, peças e períodos antes de atribuir o CTR baixo a uma causa específica.',
 jsonb_build_array('CTR baixo é sinal para investigar, não diagnóstico definitivo.')),

('66e31009-90bb-4a06-b286-4a30a3436161'::uuid,
 'Comunicação Organizacional → Publicidade oficial → Vedação à promoção pessoal',
 'A publicidade de órgãos públicos deve ter caráter educativo, informativo ou de orientação social. Nomes, símbolos ou imagens não podem caracterizar promoção pessoal de autoridades ou servidores.',
 'O enunciado afirma que a promoção pessoal seria possível “sem violar impessoalidade”, conclusão incompatível com a própria vedação constitucional.',
 'A assessoria pode divulgar políticas, agendas e resultados de interesse público, inclusive identificar autoridades quando isso for informativamente necessário. Não pode usar a estrutura oficial para construir culto pessoal ou atribuir ação estatal como favor individual.'||E'\n\n'||'Como o item autoriza finalidade promocional, está errado.',
 'A banca tenta tratar divulgação institucional legítima e autopromoção como se fossem a mesma coisa.',
 'Observe a finalidade predominante da peça: orientar e informar é permitido; enaltecer a pessoa do gestor viola impessoalidade.',
 jsonb_build_array('Publicidade oficial informa ações do Estado, não promove seus agentes.')),

('6b209837-0fa2-4fea-80d1-ed55b0f862c9'::uuid,
 'Comunicação Organizacional → Métricas digitais → Alcance e impressões',
 'Alcance contabiliza usuários ou contas únicas expostas ao conteúdo. Impressões contabilizam todas as exibições, inclusive repetições para a mesma pessoa.',
 'A palavra “sempre” e a equivalência proposta estão erradas porque um único usuário pode produzir várias impressões.',
 'Se dez pessoas visualizarem uma peça duas vezes cada, o alcance poderá ser dez e as impressões vinte. Os números só coincidem quando cada usuário gera exatamente uma exibição no universo medido.'||E'\n\n'||'Logo, impressões não equivalem necessariamente a pessoas únicas e o item está errado.',
 'A banca confunde exposição total com público exclusivo.',
 'Monte um exemplo com visualizações repetidas: ele revela rapidamente por que impressões costumam ser iguais ou superiores ao alcance.',
 jsonb_build_array('Alcance = usuários únicos; impressões = exibições totais.')),

('6fd3fefc-e7ed-4dcb-a50a-d17e97c3930e'::uuid,
 'Comunicação Organizacional → Planejamento digital → Definição de KPI',
 'KPI é um indicador-chave escolhido para acompanhar um objetivo relevante. Ele deve ser definido no planejamento, juntamente com meta, fonte de dados, periodicidade e critério de sucesso.',
 'O erro está em escolher o KPI somente depois da campanha para privilegiar o número mais favorável, prática que impede avaliação objetiva.',
 'Sem indicador previamente ligado ao objetivo, qualquer resultado pode ser selecionado para construir aparência de sucesso. Definir antes permite comparar o desempenho observado com o que a ação pretendia alcançar.'||E'\n\n'||'Como o item descreve seleção oportunista posterior, e não gestão por indicadores, está errado.',
 'A armadilha confunde análise posterior de dados com definição posterior do próprio critério de sucesso.',
 'Associe nesta ordem: objetivo → KPI → meta → coleta → avaliação. Se o KPI surgir só ao final, há viés de seleção.',
 jsonb_build_array('KPI é definido antes da execução e ligado a um objetivo.')),

('77d94068-d5bd-4c80-a6b5-0e04f962b9fd'::uuid,
 'Comunicação Organizacional → Públicos estratégicos → Público externo',
 'Público externo inclui grupos que não integram a estrutura funcional cotidiana, mas mantêm interesse, influência ou relacionamento com a organização.',
 'Imprensa, sociedade, comunidade científica, fornecedores, governo, usuários e parceiros são grupos externos com vínculos distintos e demandas próprias.',
 'A classificação não significa que todos recebem a mesma mensagem. Usuários buscam serviços, imprensa procura informação verificável, fornecedores negociam condições e parceiros compartilham projetos.'||E'\n\n'||'Como os grupos listados estão fora da estrutura interna e se relacionam estrategicamente com a instituição, o item está certo.',
 '',
 'Classifique o público pela posição em relação à estrutura e depois identifique interesse, influência e canal adequado a cada grupo.',
 jsonb_build_array('Público externo não é homogêneo; reúne diferentes relações com a organização.')),

('79157cc1-e503-41fb-989b-32ee63a7402a'::uuid,
 'Comunicação Organizacional → Métricas digitais → Conversão',
 'Conversão ocorre quando o usuário realiza a ação definida como objetivo da jornada ou campanha. A ação pode ser comercial, informativa ou de serviço, como compra, inscrição, cadastro, download ou envio de formulário.',
 'Todos os exemplos citados representam comportamentos observáveis que podem ser configurados como objetivo de uma ação digital.',
 'O conceito não se limita a venda. Em um órgão público, concluir um agendamento ou baixar uma cartilha pode ser conversão; em uma campanha educacional, inscrever-se em atividade também.'||E'\n\n'||'Como o item define conversão pela realização da ação desejada, está certo.',
 '',
 'Identifique primeiro qual comportamento foi definido como objetivo; só depois conte as ações concluídas como conversões.',
 jsonb_build_array('Conversão é a conclusão da ação desejada, não necessariamente uma compra.')),

('7a888e3d-ac56-4730-9a95-74cb91b66bf1'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Finalidade cidadã',
 'Comunicação pública organiza informação e diálogo sobre assuntos de interesse coletivo. Seus eixos incluem cidadania, transparência, utilidade social, participação e prestação de contas.',
 'O item contrapõe corretamente finalidade pública e promoção pessoal de autoridades.',
 'Canais estatais devem explicar direitos, serviços, políticas e decisões, permitindo que cidadãos participem e fiscalizem. A impessoalidade impede apropriação promocional dessa estrutura por agentes políticos.'||E'\n\n'||'A prioridade indicada coincide com os princípios da comunicação pública, portanto o item está certo.',
 '',
 'Pergunte quem recebe o benefício principal da mensagem: se for o cidadão e o interesse coletivo, há finalidade pública; se for a imagem pessoal do gestor, há desvio.',
 jsonb_build_array('Comunicação pública é orientada ao cidadão, não à autopromoção.')),

('8bfaad04-b8c3-45c3-8a7d-f7cc48d49be5'::uuid,
 'Comunicação Organizacional → Publicidade oficial → Finalidades constitucionais',
 'A publicidade dos atos, programas, obras, serviços e campanhas dos órgãos públicos deve possuir caráter educativo, informativo ou de orientação social e respeitar a impessoalidade.',
 'A enumeração “educativo, informativo ou de orientação social” reproduz as finalidades admitidas para a publicidade institucional pública.',
 'Uma campanha pode ensinar prevenção, informar a abertura de serviço ou orientar procedimento. Essas finalidades servem à coletividade e se distinguem da promoção de nomes, símbolos ou imagens pessoais.'||E'\n\n'||'Como o item apresenta corretamente os três caracteres constitucionais, está certo.',
 '',
 'Ao avaliar publicidade oficial, confronte sua finalidade com o trio educativo–informativo–orientação social e verifique impessoalidade.',
 jsonb_build_array('Publicidade oficial: educação, informação ou orientação social.')),

('970cb2ed-5b12-4722-bd31-5abdc9111fd3'::uuid,
 'Comunicação Organizacional → Comunicação Pública → Acesso a direitos e participação',
 'Comunicação pública deve tornar a ação estatal compreensível e utilizável. Isso inclui orientar sobre direitos, serviços e políticas, publicar dados e oferecer canais de escuta e participação.',
 'Todos os objetos enumerados — direitos, serviços, políticas, dados e participação — possuem utilidade coletiva e integram a relação entre Estado e cidadão.',
 'Informar a existência de um direito sem explicar como exercê-lo é insuficiente. Da mesma forma, abrir canal sem dar retorno não consolida diálogo público. Facilitar acesso significa reduzir barreiras informacionais e operacionais.'||E'\n\n'||'A finalidade cidadã descrita está correta.',
 '',
 'Verifique se a comunicação permite ao cidadão compreender, agir, participar ou fiscalizar; esses efeitos distinguem utilidade pública de mera visibilidade institucional.',
 jsonb_build_array('Comunicação pública deve orientar ação e participação cidadã.')),

('a3d639de-73c4-4b5f-ac18-645a69b0b2cd'::uuid,
 'Comunicação Organizacional → Métricas digitais → Métricas de vaidade',
 'Métricas de vaidade são números visualmente expressivos que, isoladamente, não demonstram avanço no objetivo estratégico. Curtidas podem indicar reação, mas precisam ser relacionadas a meta, público e comportamento esperado.',
 'A expressão “podem ser insuficientes” é tecnicamente adequada porque reconhece o limite de curtidas isoladas sem negar toda utilidade à métrica.',
 'Uma campanha voltada a inscrições não pode ser considerada bem-sucedida apenas porque recebeu muitas curtidas. É preciso observar cliques, conversões ou outro indicador vinculado ao objetivo.'||E'\n\n'||'Como o item exige interpretação contextual dos dados, está certo.',
 '',
 'Para cada métrica, escreva qual decisão ela informa e qual objetivo acompanha. Se não houver conexão, o número pode ser apenas vaidade.',
 jsonb_build_array('Métrica só é estratégica quando responde a um objetivo.')),

('aab10cce-ff57-407f-b549-a151988f4ea1'::uuid,
 'Comunicação Organizacional → Comunicação Integrada → Coerência entre canais',
 'Comunicação integrada coordena mensagens, responsabilidades e canais para reduzir contradições entre os fluxos interno, externo, administrativo, institucional e digital.',
 'O item associa integração à coerência entre diferentes canais e dimensões, que é precisamente sua finalidade.',
 'Integração não exige repetir a mesma peça em todos os meios. A mensagem pode ser adaptada ao público e ao formato, desde que preserve objetivos e informações centrais.'||E'\n\n'||'Ao defender coerência, e não uniformidade mecânica, o enunciado está certo.',
 '',
 'Diferencie consistência de cópia: integrar significa coordenar e adaptar sem produzir mensagens incompatíveis.',
 jsonb_build_array('Comunicação integrada preserva coerência com adaptação a canais e públicos.')),

('ab276b34-6f3a-49c1-b71f-bea5ea91bbf9'::uuid,
 'Comunicação Organizacional → Planejamento digital → Indicadores-chave',
 'KPI não é qualquer dado coletado, mas o indicador selecionado por sua capacidade de demonstrar progresso em relação a uma meta estratégica.',
 'O trecho “ainda que não esteja relacionado aos objetivos” elimina o requisito que transforma uma métrica comum em indicador-chave.',
 'Plataformas oferecem numerosos números, como visualizações, seguidores e tempo de sessão. Apenas os que ajudam a avaliar um objetivo prioritário devem ser tratados como KPI naquele planejamento.'||E'\n\n'||'Como o item chama qualquer dado disponível de indicador-chave, está errado.',
 'A banca confunde disponibilidade da métrica com relevância gerencial.',
 'Teste o indicador com a pergunta “qual objetivo ele permite avaliar?”. Sem resposta direta, não é KPI para aquela ação.',
 jsonb_build_array('Todo KPI é métrica, mas nem toda métrica é KPI.')),

('b852164b-d953-40db-8feb-8ed25f2b72a4'::uuid,
 'Comunicação Organizacional → Métricas digitais → Taxa de conversão',
 'Taxa de conversão expressa a proporção do universo elegível que realizou a ação desejada. O denominador pode ser visitantes, usuários impactados ou outra base coerente com a definição analítica.',
 'O item relaciona corretamente o número de conversões ao conjunto de usuários expostos ou visitantes da ação.',
 'Contar apenas conversões absolutas não permite comparar campanhas de tamanhos diferentes. A taxa normaliza o resultado pelo universo adotado, desde que numerador e denominador pertençam ao mesmo recorte.'||E'\n\n'||'Como a relação proporcional e sua finalidade foram descritas corretamente, o item está certo.',
 '',
 'Confira se numerador, denominador, período e público usam o mesmo recorte antes de interpretar uma taxa de conversão.',
 jsonb_build_array('Taxa de conversão = conversões ÷ universo considerado × 100.')),

('bb1dd676-24db-4f0f-9b8e-a1a9a6320217'::uuid,
 'Comunicação Organizacional → Redação institucional → Clareza e imagem',
 'Texto jornalístico institucional deve favorecer compreensão rápida, concisão e precisão. Complexidade desnecessária não demonstra competência técnica; frequentemente afasta o público e prejudica acesso à informação.',
 'O erro é atribuir valor reputacional à linguagem complexa apenas por ela parecer técnica.',
 'A importância de uma pesquisa deve ser demonstrada por evidências, impacto e explicação adequada, não por jargão. Quando termos especializados forem indispensáveis, precisam ser contextualizados.'||E'\n\n'||'Como o item recomenda dificuldade textual como estratégia de valorização institucional, contraria linguagem cidadã e está errado.',
 'A banca associa artificialmente sofisticação vocabular a credibilidade.',
 'Avalie se cada termo complexo é necessário para precisão. Se puder ser explicado ou substituído sem perda, a forma clara é preferível.',
 jsonb_build_array('Credibilidade vem de precisão e evidência, não de texto rebuscado.')),

('c892f326-ffa1-4b50-8b13-da96582a0e51'::uuid,
 'Comunicação Organizacional → Transparência digital → Dados abertos',
 'Dados abertos são disponibilizados em formato acessível, estruturado e reutilizável, com condições que permitem consulta, processamento e redistribuição, ressalvadas restrições legais.',
 'O item vincula corretamente abertura dos dados a transparência, reutilização e controle público.',
 'Quando bases podem ser baixadas e processadas, sociedade, imprensa e pesquisadores conseguem cruzar informações, desenvolver aplicações e fiscalizar políticas. Um PDF apenas visualizável nem sempre oferece a mesma capacidade de reúso.'||E'\n\n'||'Os benefícios indicados decorrem do formato aberto e o item está certo.',
 '',
 'Diferencie dado apenas publicado de dado aberto: procure formato processável, acesso, documentação e possibilidade de reutilização.',
 jsonb_build_array('Dado aberto deve poder ser acessado, processado e reutilizado.')),

('d5f89981-2783-4f9b-ba76-aad68a5c8930'::uuid,
 'Comunicação Organizacional → Transparência científica → Dados financiados com recursos públicos',
 'Pesquisas financiadas publicamente estão submetidas à diretriz de transparência e difusão do conhecimento, embora proteção de dados pessoais, segurança, segredo industrial e propriedade intelectual possam justificar restrições específicas.',
 'As expressões “por regra, indisponíveis” e “sigilo prevalece de forma absoluta” transformam exceções justificadas em proibição geral.',
 'O financiamento público reforça o interesse social em resultados e dados, observados requisitos éticos e jurídicos. Patente em processamento ou informação estratégica pode limitar divulgação, mas não torna todo dado científico sigiloso.'||E'\n\n'||'Como o item elimina a análise caso a caso e impõe sigilo absoluto, está errado.',
 'A banca usa exceções reais para inverter a regra geral de acesso e divulgação científica.',
 'Desconfie de “todo”, “sempre” e “absoluto”. Identifique qual fundamento concreto autorizaria restringir aquela informação específica.',
 jsonb_build_array('Transparência é a regra; sigilo científico exige fundamento específico.')),

('d7b929ba-81e4-433e-851d-80b8e43009c8'::uuid,
 'Comunicação Organizacional → Assessoria de imprensa → Preparação de fontes',
 'A assessoria de imprensa organiza o relacionamento entre instituição e veículos. Entre suas atividades estão apurar dados, preparar materiais, orientar fontes e porta-vozes e facilitar atendimento jornalístico.',
 'Preparar porta-vozes, organizar informações e orientar o contato com a imprensa são atribuições diretamente ligadas à mediação exercida pelo assessor.',
 'A preparação reduz contradições e ajuda a fonte a compreender o contexto da entrevista. Organizar dados aumenta precisão; orientar o relacionamento respeita rotinas jornalísticas sem tentar controlar editorialmente o veículo.'||E'\n\n'||'Como o item reúne funções típicas e compatíveis da assessoria, está certo.',
 '',
 'Diferencie facilitar e preparar de censurar ou garantir publicação. A assessoria apoia o fluxo informativo, mas não controla a redação externa.',
 jsonb_build_array('Assessoria prepara fontes e informação; o veículo mantém autonomia editorial.')),

('df53427f-5b5a-4608-a419-789faf3cd8a2'::uuid,
 'Comunicação Organizacional → Comunicação pública digital → Interatividade',
 'Redes sociais permitem comunicação bidirecional entre órgão e sociedade. Moderação pode aplicar regras de convivência e remover abusos, mas não deve eliminar participação legítima para proteger a imagem de gestores.',
 'Os termos “apenas unidirecional” e “bloqueando comentários” negam a função participativa das mídias sociais públicas.',
 'Órgãos podem divulgar informações e também responder dúvidas, corrigir ruídos e receber contribuições. Bloquear toda interação impede escuta, reduz transparência e subordina o canal público ao interesse reputacional da autoridade.'||E'\n\n'||'Como o item propõe fechamento geral do diálogo, está errado.',
 'A banca confunde moderação legítima de conteúdo abusivo com supressão prévia de participação.',
 'Em canais públicos, diferencie regra objetiva de moderação de bloqueio indiscriminado a críticas e perguntas.',
 jsonb_build_array('Rede social pública deve informar e possibilitar diálogo.')),

('efbb8af9-f491-4e32-93e4-736722b826c0'::uuid,
 'Comunicação Organizacional → Jornalismo digital → SEO e encontrabilidade',
 'SEO jornalístico aplica técnicas de estrutura, títulos, palavras-chave e metadados para facilitar que conteúdo relevante seja encontrado. A otimização deve preservar clareza, veracidade e responsabilidade editorial.',
 'O item condiciona a melhora de encontrabilidade à manutenção de critérios jornalísticos, relação tecnicamente correta.',
 'Um título pode refletir os termos pesquisados sem prometer algo ausente na matéria. Estrutura escaneável e descrição adequada ajudam busca e leitura, mas caça-cliques e repetição artificial de palavras prejudicam qualidade e confiança.'||E'\n\n'||'Como o enunciado não subordina conteúdo ao algoritmo, está certo.',
 '',
 'Avalie se a técnica melhora acesso ao conteúdo ou distorce a pauta para obter tráfego. SEO legítimo facilita encontro sem enganar.',
 jsonb_build_array('SEO melhora encontrabilidade; não substitui critério editorial.')),

('f05391eb-c82b-4aa2-9232-94049e5f8c13'::uuid,
 'Comunicação Organizacional → Comunicação interna → Endomarketing',
 'Comunicação interna é o campo amplo de circulação de informações, diálogo e alinhamento entre organização e trabalhadores. Endomarketing aplica princípios de marketing ao público interno, com foco frequente em engajamento, valorização e adesão.',
 'A expressão “sinônimos perfeitos em qualquer contexto” apaga a diferença de extensão entre os conceitos.',
 'Uma mensagem operacional, um canal de escuta ou uma comunicação de segurança integram comunicação interna sem necessariamente constituir endomarketing. Este é uma abordagem possível dentro de uma gestão interna mais abrangente.'||E'\n\n'||'Como o item iguala campo e vertente, está errado.',
 'A banca aproxima conceitos relacionados e transforma sobreposição parcial em identidade total.',
 'Quando dois conceitos parecerem sinônimos, compare extensão e finalidade: um pode incluir o outro sem serem equivalentes.',
 jsonb_build_array('Endomarketing pode integrar a comunicação interna, mas não a esgota.')),

('f5571337-10d5-41cb-acb1-68e1c7aa4091'::uuid,
 'Comunicação Organizacional → Métricas digitais → Cálculo de CTR',
 'Click-through rate mede a proporção de impressões que resultou em clique. Em forma percentual, calcula-se cliques divididos por impressões, multiplicados por cem.',
 'O item apresenta corretamente numerador, denominador e uso do CTR para avaliar a resposta a links, anúncios ou chamadas.',
 'Se uma chamada obtiver 50 cliques em 1.000 impressões, seu CTR será 5%. A taxa indica atratividade e adequação ao público exposto, embora não demonstre sozinha conversão ou qualidade do conteúdo final.'||E'\n\n'||'A definição está correta.',
 '',
 'Em cálculos de CTR, confirme que cliques estão no numerador e impressões no denominador; não confunda com taxa de conversão.',
 jsonb_build_array('CTR = cliques ÷ impressões × 100.')),

('f5d56d05-a78d-498c-a64c-f491d877617b'::uuid,
 'Comunicação Organizacional → Métricas digitais → Exposição única e total',
 'Alcance estima quantas pessoas ou contas distintas receberam o conteúdo; impressões registram quantas vezes o conteúdo foi exibido. Reexposição aumenta impressões sem aumentar necessariamente alcance.',
 'A distinção do item está correta ao reservar “usuários únicos” para alcance e “total de exibições” para impressões.',
 'Uma pessoa exposta três vezes conta uma vez no alcance e três nas impressões. Essa diferença permite também avaliar frequência média de exposição ao dividir impressões por alcance.'||E'\n\n'||'Como os dois indicadores foram definidos sem inversão, o item está certo.',
 '',
 'Procure as palavras “únicos” e “total”. Elas normalmente identificam alcance e impressões, respectivamente.',
 jsonb_build_array('Uma pessoa pode gerar várias impressões, mas apenas uma unidade de alcance.'))
)
UPDATE questions q SET
  detailed_topic=g.topic,concept_explanation=g.concept,decisive_evidence=g.evidence,
  answer_analysis=g.analysis,exam_trap=g.trap,similar_question_strategy=g.strategy,
  fixation_tips=g.tips,comparison_headers='{}'::jsonb,comparison_rows='[]'::jsonb,updated_at=now()
FROM guides g WHERE q.id=g.id;
