-- Conclusão da revisão autoral do banco de Comunicação Organizacional.

WITH guides(id,topic,concept,evidence,analysis,trap,strategy,tips) AS (VALUES
('fbdfa44c-6b13-44ae-9ec5-1ac85eb35e25'::uuid,
 'Comunicação Organizacional → Planejamento de comunicação → Componentes do plano',
 'Plano de comunicação transforma um diagnóstico em ação coordenada. Para isso, define o resultado pretendido, os públicos envolvidos, o conteúdo das mensagens, os meios de contato, o tempo, os responsáveis e a forma de avaliação.',
 'Objetivos, públicos, mensagens, canais, cronograma, responsáveis e indicadores formam uma sequência coerente de planejamento, execução e controle.',
 'Sem objetivo não há direção; sem público e mensagem não há estratégia de relacionamento; sem canal, cronograma e responsável não há execução; sem indicador não é possível verificar resultado.'||E'\n\n'||'O item reúne componentes essenciais e atribui corretamente ao plano a função de organizá-los, por isso está certo.',
 '',
 'Ao analisar um plano, percorra quatro perguntas: o que alcançar, com quem falar, como executar e como medir. Os campos do item respondem a todas elas.',
 jsonb_build_array('Plano de comunicação conecta objetivo, público, execução e avaliação.')),

('0e2b6e2a-3810-4306-9450-9dcfd75749a9'::uuid,
 'Comunicação Organizacional → Direito autoral → Direitos patrimoniais',
 'Direitos patrimoniais permitem ao titular autorizar ou explorar economicamente usos da obra. Diferem dos direitos morais, ligados à autoria, integridade e vínculo pessoal do criador com a obra.',
 'Reprodução, distribuição, comunicação pública e tradução são modalidades de utilização econômica que dependem da autorização patrimonial cabível.',
 'Reproduzir cria exemplares; distribuir os coloca em circulação; comunicar ao público torna a obra acessível; traduzir produz versão em outro idioma. Todas são formas pelas quais a obra pode ser explorada e, por isso, integram a esfera patrimonial.'||E'\n\n'||'A enumeração está correta.',
 '',
 'Classifique o direito pelo efeito: se controla uso e exploração econômica da obra, é patrimonial; se protege autoria e integridade, é moral.',
 jsonb_build_array('Direitos patrimoniais controlam formas de utilização econômica da obra.')),

('110a7e32-4de1-47a7-8e34-227572bdfaa2'::uuid,
 'Comunicação Organizacional → Inovação social → Comunidades e posicionamento',
 'Inovação social busca responder a necessidades coletivas por soluções que gerem impacto positivo e sustentável. A comunicação dessas ações deve dar centralidade às comunidades envolvidas e explicar compromissos e resultados.',
 'Necessidades das comunidades, impacto sustentável e posicionamento em causas são três eixos compatíveis com a divulgação de inovação social.',
 'Colocar a comunidade no centro evita comunicar a ação apenas pela perspectiva institucional. Demonstrar impacto esclarece o valor social produzido; posicionar-se em causas torna explícitos os compromissos que orientam a iniciativa.'||E'\n\n'||'Como as funções enumeradas reforçam finalidade social e coerência institucional, o item está certo.',
 '',
 'Em questões de inovação social, verifique se a comunidade aparece como sujeito da necessidade e participante da solução, não apenas como cenário de promoção da organização.',
 jsonb_build_array('Inovação social parte de necessidades coletivas e busca impacto sustentável.')),

('157fa8d6-d4d0-409a-92d7-3d24e14c1c0a'::uuid,
 'Comunicação Organizacional → Difusão de inovação → Público e prova social',
 'Comunicar inovação tecnológica exige conhecer necessidades, linguagem e canais do público. Disseminação em comunidades e prova social reduzem incerteza ao mostrar adoção, experiência ou validação por outros atores.',
 'Entender o público-alvo, considerar redes comunitárias e usar provas sociais são estratégias coerentes para facilitar compreensão e confiança em uma inovação.',
 'Tecnologia não se difunde apenas por suas características técnicas. A comunicação precisa mostrar aplicação e benefício no contexto do destinatário; relatos, demonstrações e casos reais podem evidenciar utilidade.'||E'\n\n'||'Como o item combina segmentação, circulação social e evidência de adoção, está certo.',
 '',
 'Antes de avaliar uma estratégia de difusão, identifique para quem a inovação resolve um problema, quem influencia sua adoção e qual evidência reduz o risco percebido.',
 jsonb_build_array('Difusão de inovação depende de relevância para o público e evidências de uso.')),

('5cbe7e4a-e823-49cb-b09d-f88eee098463'::uuid,
 'Comunicação Organizacional → Planejamento estratégico → Controle operacional por feedback',
 'No nível operacional, controle compara padrões ou metas planejadas com resultados efetivamente obtidos. O feedback devolve informação sobre o desempenho e permite identificar desvio e corrigir a execução.',
 'A diferença entre valor planejado e valor real é justamente o erro ou desvio que o mecanismo de feedback deve revelar.',
 'Se a meta era alcançar determinado resultado e a medição mostra valor distinto, essa distância orienta análise e ajuste. O feedback não é simples opinião: é informação de retorno usada no controle do processo.'||E'\n\n'||'O item descreve corretamente essa comparação e está certo.',
 '',
 'Em questões de controle, procure três elementos: padrão planejado, resultado medido e ação corretiva decorrente da diferença.',
 jsonb_build_array('Feedback operacional compara realizado e planejado para corrigir desvios.')),

('90c0b0f1-cd6a-4e6c-bb0c-e282182c3b6e'::uuid,
 'Comunicação Organizacional → Stakeholders → Diálogo e gestão de erros',
 'Comunicação com stakeholders deve ser aberta, ética e responsiva, considerando expectativas e contribuições. Isso não significa prometer infalibilidade; significa reconhecer, corrigir e aprender com erros quando ocorrerem.',
 'A expressão “eximir-se de erros” impõe resultado absoluto impossível e não constitui requisito técnico de uma relação estratégica.',
 'Ouvir expectativas e agregar valor são práticas adequadas. Entretanto, organizações podem errar mesmo com bons processos; a conduta esperada é transparência, responsabilização e correção, e não a garantia de nunca cometer falhas.'||E'\n\n'||'Como uma única condição absoluta invalida o conjunto da assertiva, o item está errado.',
 'A banca inclui várias práticas corretas e acrescenta uma exigência impossível para tornar o item incorreto.',
 'Em itens longos, teste cada oração separadamente. Um termo absoluto incompatível basta para invalidar toda a proposição do tipo certo/errado.',
 jsonb_build_array('Gestão ética não exige infalibilidade; exige resposta responsável aos erros.')),

('c59fe3da-6c60-492c-b43e-ef404fb2b797'::uuid,
 'Comunicação Organizacional → Diagnóstico estratégico → Ambiente interno',
 'Diagnóstico estratégico examina condições internas e externas que influenciam os objetivos. No ambiente interno, identifica forças e fraquezas; no externo, oportunidades e ameaças.',
 'O item delimita o contexto interno e menciona forças, potencialidades, fragilidades e fraquezas, categorias próprias dessa análise.',
 'Conhecer capacidades internas mostra o que pode ser aproveitado e quais limitações precisam ser tratadas para alcançar objetivos. A expressão final sobre oportunidades de realização não altera o fato de que o núcleo descrito é o diagnóstico interno.'||E'\n\n'||'A relação entre análise interna e planejamento está correta.',
 '',
 'Na matriz SWOT, classifique forças e fraquezas como internas; oportunidades e ameaças como externas. Depois confira qual ambiente o item realmente descreve.',
 jsonb_build_array('Ambiente interno: forças e fraquezas; externo: oportunidades e ameaças.')),

('d1ba91b5-2af2-4988-9ea6-6f395b3827ae'::uuid,
 'Comunicação Organizacional → Planejamento estratégico → Missão, visão e objetivos',
 'Planejamento estratégico utiliza missão, visão, valores, objetivos e análise dos ambientes para orientar escolhas e construir capacidades diferenciadoras. “Sucessos e conquistas” são resultados possíveis, não componentes conceituais de um trinômio orientador.',
 'O erro está na fórmula “missão, sucessos e conquistas”, que substitui elementos de direção estratégica por resultados genéricos.',
 'Missão esclarece a razão de existir; visão projeta o estado futuro desejado; objetivos traduzem direção em resultados. Sucessos passados podem informar o diagnóstico, mas não ocupam automaticamente essas funções.'||E'\n\n'||'Como o trinômio apresentado não corresponde à estrutura de planejamento, o item está errado.',
 'A banca combina um termo técnico verdadeiro, “missão”, com expressões positivas sem função conceitual equivalente.',
 'Não aceite uma lista apenas porque seus termos parecem desejáveis. Defina a função de cada componente dentro do planejamento.',
 jsonb_build_array('Missão orienta propósito; visão orienta futuro; objetivos orientam resultados.')),

('1e7025c7-2bc0-461a-ba0e-26be3a04a149'::uuid,
 'Comunicação Organizacional → Comunicação interna → Papel do colaborador',
 'Comunicação organizacional estratégica conecta trabalho cotidiano, objetivos institucionais e resultados coletivos. Ao compreender sua contribuição, o colaborador consegue alinhar decisões e prioridades.',
 'Conscientizar o colaborador sobre seu papel relaciona informação interna a propósito, responsabilidade e coordenação organizacional.',
 'A função vai além de transmitir avisos. Explicar por que uma tarefa importa, como áreas se conectam e qual resultado é esperado aumenta capacidade de atuação coerente e participação.'||E'\n\n'||'Como o enunciado descreve uma contribuição estratégica legítima da comunicação, está certo.',
 '',
 'Diferencie comunicação meramente operacional de estratégica: a segunda conecta informação, propósito e contribuição para objetivos.',
 jsonb_build_array('Comunicação estratégica ajuda o colaborador a compreender sua contribuição.')),

('5420d26b-ee19-405f-90b8-a0b8e65a5108'::uuid,
 'Comunicação Organizacional → Linguagem simples → Formalidade no atendimento público',
 'Linguagem simples busca clareza, concisão e acessibilidade. Formalidade diz respeito à adequação, urbanidade e respeito da interação; os dois eixos podem coexistir.',
 'O erro está em concluir que inclusão e acessibilidade exigem adoção de informalidade no tratamento ao cidadão.',
 'É possível empregar frases diretas, explicar termos e organizar instruções mantendo tratamento respeitoso e compatível com o contexto institucional. Em certas situações, tom mais próximo é adequado; em outras, a formalidade continua necessária.'||E'\n\n'||'Como o item transforma linguagem simples em abandono obrigatório da formalidade, está errado.',
 'A banca confunde simplicidade linguística com grau de formalidade social.',
 'Avalie separadamente clareza do texto e tratamento usado na relação. Uma mensagem pode ser simples e formal ao mesmo tempo.',
 jsonb_build_array('Linguagem simples não é sinônimo de linguagem informal.')),

('91732760-d962-48e5-b3ec-25460c6f94ec'::uuid,
 'Comunicação Organizacional → Comunicação pública → Estado e sociedade',
 'Comunicação pública abrange processos comunicacionais relacionados a temas de interesse coletivo. Pode envolver Estado, cidadãos, organizações sociais, empresas e demais atores que participam da esfera pública.',
 'O item associa comunicação pública ao interesse público e afirma expressamente que ela não envolve apenas o Estado.',
 'Comunicação governamental é uma das manifestações possíveis, mas debates, mobilização social, controle e circulação de informações de interesse comum também contam com atores não estatais.'||E'\n\n'||'Como o enunciado adota compreensão ampla e centrada na coletividade, está certo.',
 '',
 'Não classifique comunicação pública somente pelo emissor estatal. Observe se o assunto e a finalidade pertencem à esfera de interesse coletivo.',
 jsonb_build_array('Comunicação pública envolve Estado e sociedade em assuntos coletivos.')),

('9c12129a-9d69-4ee2-b658-a1cd4608285a'::uuid,
 'Comunicação Organizacional → Comunicação interna → Canais e alinhamento',
 'Canais internos são meios formais ou informais usados para circular informação e promover diálogo entre organização, lideranças e trabalhadores. Exemplos incluem intranet, reuniões, boletins, aplicativos e redes corporativas.',
 'Alinhar, informar e engajar colaboradores são finalidades compatíveis com o uso eficiente desses canais.',
 'O canal permite comunicar objetivos e procedimentos, receber retorno e aproximar equipes. Sua eficiência depende de escolha adequada ao público, acesso, frequência e possibilidade de interação.'||E'\n\n'||'Como o item define corretamente meios e finalidades, está certo.',
 '',
 'Em questões sobre canais, diferencie o meio da estratégia: possuir intranet não garante alinhamento se conteúdo, acesso e retorno forem inadequados.',
 jsonb_build_array('Canal interno eficaz informa, conecta e permite alinhamento.')),

('9fb823b6-6235-48c9-8db6-5a3b9bc34615'::uuid,
 'Comunicação Organizacional → Comunicação interna → Identidade, imagem e reputação',
 'Comunicação interna pode trabalhar missão, visão e valores para alinhar colaboradores à identidade organizacional. Imagem e reputação, porém, resultam da percepção de diferentes públicos e não podem ser atribuídas de modo simples a um único foco comunicacional.',
 'A redação aproxima comunicação interna, identidade e formação de reputação “junto ao público” sem delimitar qual público nem a relação exata entre esses conceitos.',
 'A primeira parte pode ser defendida: conteúdos internos ajudam trabalhadores a compreender identidade e propósito. A segunda amplia o efeito para uma boa reputação perante o público sem esclarecer mediação, público interno ou externo e coerência das práticas.'||E'\n\n'||'Essa ambiguidade impede julgamento objetivo, razão pela qual a banca anulou o item.',
 'A dificuldade não é uma simples troca de conceito, mas a falta de delimitação que permite leituras defensáveis distintas.',
 'Em questão anulada, identifique quais leituras concorrentes tornam impossível atribuir certo ou errado com segurança.',
 jsonb_build_array('Comunicação interna trabalha identidade; reputação depende da percepção acumulada de públicos e práticas.')),

('ef073a35-5e81-4aad-a1be-e004565293e3'::uuid,
 'Comunicação Organizacional → Comunicação interna → Objetivos, confiança e motivação',
 'Comunicação interna esclarece prioridades, decisões e objetivos para reduzir incerteza e coordenar o trabalho. Quando é coerente e confiável, pode fortalecer pertencimento, confiança e motivação.',
 'Informar claramente os colaboradores sobre os objetivos da organização é uma incumbência compatível com alinhamento e engajamento interno.',
 'Quem compreende para onde a organização se dirige consegue relacionar suas tarefas aos resultados coletivos. Clareza também reduz rumores e interpretações contraditórias, favorecendo confiança nas lideranças e nos processos.'||E'\n\n'||'O item descreve corretamente essa função e está certo.',
 '',
 'Em questões de comunicação interna, procure a cadeia informação clara → compreensão do objetivo → alinhamento e confiança; ela explica o efeito estratégico.',
 jsonb_build_array('Objetivos compreendidos ajudam a alinhar trabalho, confiança e motivação.'))
)
UPDATE questions q SET
  detailed_topic=g.topic,concept_explanation=g.concept,decisive_evidence=g.evidence,
  answer_analysis=g.analysis,exam_trap=g.trap,similar_question_strategy=g.strategy,
  fixation_tips=g.tips,comparison_headers='{}'::jsonb,comparison_rows='[]'::jsonb,updated_at=now()
FROM guides g WHERE q.id=g.id;
