-- Substitui comentários genéricos de TI por correções específicas e corrige
-- três gabaritos que contrariavam a própria definição técnica do enunciado.

WITH corrections(id,correct,explanation,concept,evidence,analysis,trap,strategy,memory) AS (VALUES
  ('0eaaaf8d-29c0-4d8e-8dc5-b539804a1a25'::uuid,'Errado',
   'Errado. GET é idempotente: repeti-lo deve produzir o mesmo efeito pretendido no servidor. POST, em regra, não é idempotente; duas requisições iguais podem criar dois recursos ou executar a mesma ação duas vezes.',
   'Idempotência significa que repetir uma operação produz no servidor o mesmo efeito pretendido de executá-la uma vez. No HTTP, GET, PUT e DELETE possuem semântica idempotente; POST não oferece essa garantia.',
   'O erro está em reunir GET e POST na afirmação “são considerados idempotentes”.',
   'A primeira metade é verdadeira para GET. O problema é estender a propriedade a POST: chamadas POST repetidas podem gerar novos identificadores, cobranças ou registros distintos. Como o item atribui idempotência aos dois métodos, ele está errado.',
   'A banca combina um método idempotente com outro que não possui essa garantia e usa o plural para transferir a característica de GET para POST.',
   'Em questões de métodos HTTP, classifique separadamente segurança e idempotência. Não conclua que POST é idempotente apenas porque uma API específica implementou uma chave de idempotência.',
   'GET é idempotente; POST, por padrão, não é.'),

  ('fc76a56c-c519-4b08-a34a-265593e6bec5'::uuid,'Certo',
   'Certo. Na Clean Architecture, entidades e casos de uso ficam nas camadas internas. Frameworks, interface, banco de dados e outros detalhes permanecem nas camadas externas e dependem do núcleo, não o contrário.',
   'A regra de dependência da Clean Architecture determina que dependências de código apontem para dentro. As regras de negócio centrais não devem conhecer framework, banco de dados, interface gráfica ou mecanismo de entrega.',
   'O item coloca entidades e casos de uso no núcleo e os declara independentes de frameworks e bancos de dados.',
   'Essa é precisamente a separação proposta pela Clean Architecture. O núcleo contém políticas de negócio estáveis; adaptadores e detalhes de infraestrutura implementam interfaces definidas em direção ao núcleo. Por isso, a afirmação está correta.',
   '',
   'Ao analisar Clean Architecture, desenhe as camadas e siga a direção das dependências: detalhes externos podem conhecer abstrações internas, mas as regras de negócio não dependem dos detalhes.',
   'Clean Architecture: dependências apontam para o núcleo; negócio não depende de framework ou banco.'),

  ('86354557-fc37-471a-9de9-2774523a69e2'::uuid,'Errado',
   'Errado. Atomicidade é apenas uma das quatro propriedades ACID e significa “tudo ou nada”: a transação confirma todas as operações ou desfaz todas. Ela, isoladamente, não garante Consistência, Isolamento e Durabilidade.',
   'ACID reúne Atomicidade, Consistência, Isolamento e Durabilidade. Atomicidade impede confirmação parcial: se uma etapa falha, todas as alterações da transação devem ser revertidas.',
   'O item trata Atomicidade como garantia genérica de que a transação “siga o princípio ACID”.',
   'A formulação confunde uma propriedade com o conjunto inteiro. Uma transação pode ser atômica e ainda violar uma restrição de consistência, sofrer anomalia de isolamento ou não ter durabilidade. Atomicidade responde somente pelo comportamento de tudo ou nada; por isso, o item está errado.',
   'A armadilha é usar a sigla ACID no próprio conceito de Atomicidade para fazê-la parecer responsável pelas quatro propriedades.',
   'Em questões de ACID, associe cada letra ao problema que resolve: A = confirmação parcial; C = estado válido; I = concorrência; D = persistência após commit.',
   'Atomicidade = todas as operações confirmam ou todas são desfeitas.'),

  ('ae50b034-5b64-4406-a5fc-4ab1b5e8a51e'::uuid,'Errado',
   'Errado. Isolamento controla a interferência entre transações concorrentes. A preservação de restrições, como chaves e integridade referencial, pertence principalmente à Consistência.',
   'Isolamento faz transações concorrentes se comportarem, conforme o nível adotado, como se sua execução estivesse adequadamente separada. Consistência exige que cada transação leve o banco de um estado válido a outro estado válido.',
   'A expressão incorreta é “Isolamento ... propriedade de integridade de chaves”.',
   'Integridade de chave é uma restrição do estado dos dados e se relaciona à Consistência. Isolamento trata de fenômenos concorrentes, como leitura suja, leitura não repetível e fantasma. O item troca as responsabilidades de I e C em ACID e, portanto, está errado.',
   'A banca troca duas propriedades verdadeiras da mesma sigla: Isolamento por Consistência.',
   'Quando a questão mencionar concorrência ou visibilidade entre transações, pense em Isolamento; quando mencionar restrições e estado válido, pense em Consistência.',
   'Isolamento = concorrência; Consistência = regras e estado válido.'),

  ('ceb5014e-2c45-4e4f-afbf-d768aea6c1d8'::uuid,'Certo',
   'Certo. Consistência exige que a transação leve o banco de um estado válido a outro, preservando as restrições declaradas. Isso inclui chaves primárias, estrangeiras, unicidade e outras regras de integridade.',
   'Na propriedade C de ACID, uma transação válida não deixa o banco em estado incompatível com suas restrições. O SGBD aplica constraints; a lógica transacional também deve respeitar as invariantes do domínio.',
   'O item relaciona Consistência à integridade de chaves.',
   'Chaves são exemplos de restrições que definem estados válidos do banco. Se uma transação tentasse duplicar uma chave primária ou criar referência estrangeira inválida, a restrição impediria a confirmação. A associação feita pelo item é correta.',
   '',
   'Em ACID, associe Consistência à passagem estado válido → estado válido e procure no item restrições, chaves ou invariantes do domínio.',
   'Consistência preserva restrições e invariantes entre o início e o fim da transação.'),

  ('6f25b845-2328-48db-be58-955426d401b7'::uuid,'Certo',
   'Certo. O API Gateway oferece um ponto de entrada para clientes e pode concentrar roteamento, autenticação, limitação de requisições, composição de respostas e outras preocupações transversais.',
   'Em microsserviços, o API Gateway funciona como fachada na borda do sistema. Ele recebe chamadas externas e as encaminha aos serviços apropriados, evitando que o cliente precise conhecer todos os endereços internos.',
   'O item atribui ao gateway centralização da entrada, roteamento, autenticação e rate limiting.',
   'Todas essas são responsabilidades usuais de um API Gateway. Isso não significa centralizar a lógica de negócio dos microsserviços: o componente centraliza o acesso externo e políticas transversais. Com esse alcance, a proposição está correta.',
   '“Centraliza” não significa transformar os microsserviços em monólito; o que se centraliza é a porta de entrada e certas políticas de borda.',
   'Em questões de API Gateway, separe preocupações de borda — roteamento, autenticação e rate limiting — da lógica de negócio, que continua nos serviços.',
   'API Gateway = entrada externa única e políticas transversais; negócio permanece distribuído.'),

  ('0011929e-26d1-41c7-9889-c0844158c352'::uuid,'Errado',
   'Errado. “Atomicidade” é propriedade de transações ACID, não princípio SOLID. Além disso, o princípio aberto/fechado determina que entidades sejam abertas para extensão e fechadas para modificação.',
   'SOLID reúne Responsabilidade Única, Aberto/Fechado, Substituição de Liskov, Segregação de Interfaces e Inversão de Dependência. Atomicidade não integra esse conjunto.',
   'O item inventa o princípio SOLID “Atomicidade” e ainda diz “aberta para modificação”.',
   'Há dois erros. Atomicidade pertence ao contexto ACID. A descrição tenta lembrar o Open/Closed Principle, mas o inverte: novas variações devem ser adicionadas por extensão, sem exigir alteração direta do código estável. Logo, o item está errado.',
   'A banca mistura a letra A de ACID com a sigla SOLID e inverte a fórmula do princípio aberto/fechado.',
   'Primeiro expanda a sigla SOLID; depois confira OCP: aberto para extensão, fechado para modificação.',
   'Atomicidade é ACID. OCP = extensão permitida, modificação evitada.'),

  ('29f33a29-0135-49dc-a10e-5d32a1552fe4'::uuid,'Errado',
   'Errado. “Isolamento” é propriedade de transações ACID, não princípio SOLID. O princípio aberto/fechado também não autoriza modificação direta: ele favorece extensão sem alterar o código existente.',
   'Os princípios SOLID são SRP, OCP, LSP, ISP e DIP. Isolamento corresponde à letra I de ACID e trata da concorrência entre transações.',
   'O item chama Isolamento de princípio SOLID e associa a ele abertura para modificação.',
   'A afirmação cruza dois conteúdos diferentes. Isolamento pertence a bancos de dados; em SOLID, a ideia mais próxima da frase seria OCP, cuja regra é exatamente ser aberto para extensão e fechado para modificação. Por isso, o item está errado.',
   'A letra I aparece em ACID e SOLID, mas representa conceitos distintos: Isolamento em ACID e Segregação de Interfaces em SOLID.',
   'Antes de julgar, expanda as duas siglas: no contexto de projeto, procure SRP, OCP, LSP, ISP e DIP; no contexto transacional, procure ACID.',
   'Em SOLID, I = segregação de interfaces; em ACID, I = isolamento.'),

  ('5767e258-356b-48d3-8c45-8095eab5f108'::uuid,'Errado',
   'Errado. “Consistência” é propriedade de transações ACID, não princípio SOLID. A regra “aberta para extensão e fechada para modificação” pertence ao Open/Closed Principle.',
   'Consistência, em ACID, preserva restrições e estados válidos. SOLID não possui princípio chamado Consistência; suas letras representam SRP, OCP, LSP, ISP e DIP.',
   'O item inclui “Consistência” em SOLID e afirma que a classe deve ser aberta para modificação direta.',
   'A proposição mistura ACID com SOLID e ainda inverte OCP. Extensões podem acrescentar comportamento por abstrações, composição ou polimorfismo, enquanto a modificação direta do código estável deve ser evitada. Assim, o item está errado.',
   'A banca usa um termo positivo e conhecido de ACID dentro de outra sigla para criar um princípio inexistente.',
   'Ao encontrar um suposto princípio SOLID, confira seu nome na expansão da sigla e só então avalie a descrição fornecida pelo item.',
   'Consistência pertence a ACID; em SOLID, OCP protege o código estável contra modificação direta.'),

  ('331d9b2a-2387-46ef-9584-2cd5270e3dd3'::uuid,'Errado',
   'Errado. Backup diferencial copia as alterações realizadas desde o último backup completo. Ele não reinicia sua referência após um backup incremental e, em geral, não limpa o atributo de arquivamento.',
   'No backup incremental, cada execução copia alterações desde o último backup completo ou incremental. No diferencial, todas as execuções continuam comparando com o último backup completo.',
   'O item diz “desde o último backup completo ou incremental” ao definir o diferencial.',
   'A parte “ou incremental” descreve o encadeamento do backup incremental, não do diferencial. Por isso, diferenciais sucessivos tendem a crescer até o próximo backup completo. A afirmação também erra ao dizer que os arquivos são marcados como salvos. O item está errado.',
   'A banca inseriu “ou incremental” na definição do diferencial, misturando os dois métodos.',
   'Pergunte qual é a base de comparação: diferencial → último completo; incremental → último backup executado.',
   'Diferencial acumula mudanças desde o último completo.'),

  ('0afab6f8-d412-4000-b689-af8c0f6e5b6d'::uuid,'Certo',
   'Certo. HTTPS é HTTP protegido por TLS — historicamente chamado SSL/TLS — e usa por padrão a porta TCP 443. O canal oferece confidencialidade, integridade e autenticação do servidor por certificado.',
   'TLS protege a comunicação em trânsito. Após o handshake negociar parâmetros e chaves, os registros da sessão são cifrados e autenticados; o certificado permite ao cliente validar a identidade apresentada pelo servidor.',
   'O item associa HTTPS, SSL/TLS, confidencialidade, integridade e porta 443.',
   'Essa associação está correta. SSL é a tecnologia histórica e está obsoleta, mas a expressão “SSL/TLS” é usada para a família de protocolos; nas conexões atuais deve-se empregar TLS. A ressalva não torna falsa a descrição geral do HTTPS.',
   'A menção conjunta “SSL/TLS” não significa que versões antigas e inseguras de SSL devam ser habilitadas.',
   'Em HTTPS, memorize: HTTP sobre TLS; porta padrão 443; proteção do canal em trânsito.',
   'HTTPS = HTTP + TLS, normalmente na porta TCP 443.'),

  ('6ddac3de-8ece-407e-8e49-a29f438e7f79'::uuid,'Errado',
   'Errado. AES continua sendo uma cifra simétrica moderna e amplamente usada. Em Wi-Fi, aparece em mecanismos como CCMP no WPA2 e em suítes do WPA3; uma chave forte não é quebrada por força bruta em poucos minutos.',
   'AES é um algoritmo de cifra de bloco com chaves de 128, 192 ou 256 bits. A segurança do Wi-Fi depende também do protocolo, da senha, da autenticação e da configuração, não de uma suposta obsolescência do AES.',
   'O item chama AES de “obsoleto” e afirma quebra por força bruta “em poucos minutos”.',
   'As duas qualificações são falsas. Ataques práticos costumam explorar senha fraca, configuração ou protocolo inadequado; não representam quebra direta do espaço de chaves do AES. Por isso, o item está errado.',
   'A banca transfere vulnerabilidades de senhas ou protocolos antigos para o algoritmo AES.',
   'Diferencie algoritmo de cifra, protocolo Wi-Fi e qualidade da senha antes de atribuir a origem de uma vulnerabilidade.',
   'AES não é obsoleto; senha e configuração fracas podem comprometer o Wi-Fi sem quebrar o AES.'),

  ('aca9e8eb-472f-4c95-a997-0be0b920ed65'::uuid,'Errado',
   'Errado. RSA é um algoritmo assimétrico, não o padrão de cifra usado para proteger quadros em redes Wi-Fi. WPA2 e WPA3 empregam mecanismos baseados em cifras simétricas, como AES.',
   'RSA usa par de chaves e pode participar de autenticação ou troca de material criptográfico em outros protocolos. A proteção do enlace Wi-Fi utiliza as suítes definidas por WPA2/WPA3, e não um “padrão de segurança RSA”.',
   'O erro começa em “Em redes Wi-Fi, o padrão de segurança RSA”.',
   'A afirmação atribui a RSA uma função que ele não exerce no Wi-Fi e depois acrescenta uma alegação genérica de quebra rápida por força bruta. O tamanho e o uso de chaves exigem análise própria; não há essa classificação de RSA como padrão Wi-Fi. Logo, o item está errado.',
   'A banca mistura algoritmo assimétrico com padrão de segurança de rede sem fio.',
   'Em Wi-Fi, identifique primeiro a suíte WPA e a cifra de enlace; não trate qualquer algoritmo criptográfico como padrão Wi-Fi.',
   'RSA é assimétrico; WPA2/WPA3 protegem o enlace com mecanismos próprios, tipicamente baseados em AES.'),

  ('4862b8ed-0dae-4401-b87c-c15ae7b80038'::uuid,'Errado',
   'Errado. TCP é um protocolo de transporte orientado à conexão e confiável: usa números de sequência, confirmações, retransmissões e controle de fluxo para entregar um fluxo ordenado de bytes.',
   'A confiabilidade do TCP é obtida com confirmação de recebimento e retransmissão de segmentos perdidos, além da ordenação no destino. Isso não garante que a aplicação nunca falhe, mas diferencia TCP do serviço de melhor esforço do UDP.',
   'A palavra que invalida o item é “não confiável” aplicada ao TCP.',
   'O restante da descrição — TCP na camada de transporte — está correto. O erro pontual é negar sua confiabilidade, característica central do protocolo. Assim, a proposição inteira deve ser julgada errada.',
   'A banca mantém camada e protocolo corretos e troca apenas a característica que distingue TCP de UDP.',
   'Em transporte: TCP = conexão, ordem, confirmação e retransmissão; UDP = datagramas sem essas garantias.',
   'TCP oferece entrega confiável e ordenada do fluxo de bytes.'),

  ('9708aec0-f456-43c2-8b1f-448c6fac5e04'::uuid,'Errado',
   'Errado. A dupla negação “não não confiável” equivale a chamar UDP de confiável. UDP é um protocolo de transporte sem conexão e de melhor esforço, sem confirmação, retransmissão ou ordenação próprias.',
   'UDP preserva limites de datagramas e possui baixo overhead, mas não oferece as garantias de entrega e ordem implementadas pelo TCP. Se a aplicação precisar delas, deverá fornecê-las por outro mecanismo.',
   'O ponto decisivo é a expressão “não não confiável”, que produz sentido afirmativo.',
   'Embora acerte ao colocar UDP na camada de transporte, o item usa a dupla negação para atribuir confiabilidade ao protocolo. Como UDP não garante entrega nem sequência, a afirmação está errada.',
   'A armadilha é linguística: duas negações mudam “não confiável” para “confiável”.',
   'Leia negações sucessivas literalmente e depois compare: UDP não garante entrega, ordem ou retransmissão.',
   'UDP é de melhor esforço; a dupla negação do item o tornou incorretamente confiável.'),

  ('67f803f8-846e-43c1-84fa-0bc4d3d63816'::uuid,'Errado',
   'Errado. Uma VPN estende conectividade privada sobre uma rede pública por meio de tunelamento e, nas soluções usuais de acesso remoto ou site a site, criptografa e autentica o tráfego. Enviar os dados em texto claro não oferece a confidencialidade esperada.',
   'VPN cria um túnel lógico entre pares. Protocolos como IPsec e TLS protegem os pacotes encapsulados contra leitura e alteração durante a passagem pela rede pública.',
   'A expressão incorreta é “dados abertos em formato plaintext”.',
   'A primeira parte define corretamente a extensão de uma rede privada sobre infraestrutura pública. O erro está na consequência: o tráfego protegido atravessa a rede pública cifrado, não exposto em texto claro. Por isso, o item está errado.',
   'A banca começa com a definição correta de VPN e inverte justamente a propriedade de confidencialidade do túnel.',
   'Em questões de VPN, procure três elementos: túnel, autenticação dos pares e proteção do tráfego na rede não confiável.',
   'VPN segura não torna o tráfego público: ela o encapsula e normalmente o cifra no túnel.' )
)
UPDATE questions q SET
  correct_answer=to_jsonb(c.correct),explanation=c.explanation,
  concept_explanation=c.concept,decisive_evidence=c.evidence,answer_analysis=c.analysis,
  exam_trap=c.trap,similar_question_strategy=c.strategy,
  fixation_tips=jsonb_build_array(c.memory),comparison_headers='{}'::jsonb,
  comparison_rows='[]'::jsonb,updated_at=now()
FROM corrections c WHERE q.id=c.id;
